version: 2.1
orbs:
  node: circleci/node@5.0.2
  coveralls: coveralls/coveralls@2.2.1

jobs:
  execute_tests:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test:ci
          name: Run tests
      - coveralls/upload

workflows:
  run_tests:
    jobs:
      - execute_tests:
          filters:
            branches:
              only: main # only deploy when on main
